name: "Setup Flutter Version Management CLI"
description: "Setup the Flutter Version Management CLI, and add it to the PATH"
branding:
  icon: "triangle"
  color: "blue"
inputs:
  version:
    description: "The version to install: Default: latest"
    required: false
    default: "latest"
  token:
    description: "The GitHub token to use for the installation"
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: "composite"
  steps:
    # Run the action
    - name: Setup Flutter Version Management CLI
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: $GITHUB_ACTION_PATH/action.sh ${{ inputs.version }}
