name: "Setup Flutter Version Management CLI"
description: "Setup the Flutter Version Management CLI, and add it to the PATH"
branding:
  icon: "triangle"
  color: "blue"
inputs:
  version:
    description: "The version to install: Default: latest"
    required: false
    default: "latest"
  workspace:
    description: "The working directory to run the action in"
    required: false
    default: "{{ github.workspace }}"
runs:
  using: "composite"
  steps:
    # Run the action
    - name: Setup Flutter Version Management CLI
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: $GITHUB_ACTION_PATH/action.sh ${{ inputs.version }} ${{ inputs.workspace }}
