name: Flutter Version Management CLI

on:
  push:
    branches: [main, v*]
  pull_request:
    branches: [main, v*]
  schedule:
    # https://crontab.guru/#40_10_*_*_*
    - cron: '40 10 * * *'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest # Apple M1 Silicon
          - macos-13 # Intel Mac
          - windows-latest
        version:
          - latest
          - 3.1.5
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Setup Flutter SDK
        run: echo yes | fvm install stable
      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart
